<template>
  <div class="privacy">
    <div class="container">
      <h2 class="head"><b>Privacy & Policy</b></h2>
      <h3 class="mb-2">TaskManagement User Privacy & Policy</h3>
      <small>
        <b>Effective Date: December 1, 2021</b>
      </small>
      <h5 class="mt-2"><b>1.</b> Introduction</h5>

      <h6>
        Welcome to TaskManagement.
        <br />
        TaskManagement (“us”, “we”, or “our”) operates TaskManagement.com
        (hereinafter referred to as “Service”).
      </h6>
      <p>
        Our Privacy Policy governs your visit to TaskManagement.com, and
        explains how we collect, safeguard and disclose information that results
        from your use of our Service. We use your data to provide and improve
        Service. By using Service, you agree to the collection and use of
        information in accordance with this policy. Unless otherwise defined in
        this Privacy Policy, the terms used in this Privacy Policy have the same
        meanings as in our Terms and Conditions. Our Terms and Conditions
        (“Terms”) govern all use of our Service and together with the Privacy
        Policy constitutes your agreement with us (“agreement”).
      </p>
      <h5><b>2.</b> Definitions</h5>
      <h6>
        SERVICE means the TaskManagement.com website operated by TaskManagement.
      </h6>
      <p>
        ERSONAL DATA means data about a living individual who can be identified
        from those data (or from those and other information either in our
        possession or likely to come into our possession). USAGE DATA is data
        collected automatically either generated by the use of Service or from
        Service infrastructure itself (for example, the duration of a page
        visit). COOKIES are small files stored on your device (computer or
        mobile device). DATA CONTROLLER means a natural or legal person who
        (either alone or jointly or in common with other persons) determines the
        purposes for which and the manner in which any personal data are, or are
        to be, processed. For the purpose of this Privacy Policy, we are a Data
        Controller of your data. DATA PROCESSORS (OR SERVICE PROVIDERS) means
        any natural or legal person who processes the data on behalf of the Data
        Controller. We may use the services of various Service Providers in
        order to process your data more effectively. DATA SUBJECT is any living
        individual who is the subject of Personal Data. THE USER is the
        individual using our Service. The User corresponds to the Data Subject,
        who is the subject of Personal Data.
      </p>
      <h5><b>3.</b> Information Collection and Use</h5>
      <p>
        We collect several different types of information for various purposes
        to provide and improve our Service to you.
      </p>
      <h5><b>4.</b> Types of Data Collected</h5>
      <h6>Personal Data :</h6>
      <p>
        While using our Service, we may ask you to provide us with certain
        personally identifiable information that can be used to contact or
        identify you (“Personal Data”). Personally identifiable information may
        include, but is not limited to:
        <br />
        <b>0.1.</b> Email address
        <br />
        <b>0.2.</b> First name and last name
        <br />
        <b>0.3.</b> Phone number
        <br />
        <b>0.4.</b> Address, Country, State, Province, ZIP/Postal code, City
        <br />
        <b>0.5.</b> Cookies and Usage Data
        <br />
        We may use your Personal Data to contact you with newsletters, marketing
        or promotional materials and other information that may be of interest
        to you. You may opt out of receiving any, or all, of these
        communications from us by following the unsubscribe link. Usage Data We
        may also collect information that your browser sends whenever you visit
        our Service or when you access Service by or through any device (“Usage
        Data”). This Usage Data may include information such as your computer’s
        Internet Protocol address (e.g. IP address), browser type, browser
        version, the pages of our Service that you visit, the time and date of
        your visit, the time spent on those pages, unique device identifiers and
        other diagnostic data. When you access Service with a device, this Usage
        Data may include information such as the type of device you use, your
        device unique ID, the IP address of your device, your device operating
        system, the type of Internet browser you use, unique device identifiers
        and other diagnostic data.
      </p>
      <h6>Tracking Cookies Data</h6>
      <p>
        We use cookies and similar tracking technologies to track the activity
        on our Service and we hold certain information. Cookies are files with a
        small amount of data which may include an anonymous unique identifier.
        Cookies are sent to your browser from a website and stored on your
        device. Other tracking technologies are also used such as beacons, tags
        and scripts to collect and track information and to improve and analyze
        our Service. You can instruct your browser to refuse all cookies or to
        indicate when a cookie is being sent. However, if you do not accept
        cookies, you may not be able to use some portions of our Service.
        Examples of Cookies we use:

        <br />
        <b>0.1.</b> Session Cookies: We use Session Cookies to operate our
        Service.

        <br />
        <b>0.2.</b> Preference Cookies: We use Preference Cookies to remember
        your preferences and various settings.

        <br /><b>0.3.</b> Security Cookies: We use Security Cookies for security
        purposes.

        <br />
        <b>0.4.</b> Advertising Cookies: Advertising Cookies are used to serve
        you with advertisements that may be relevant to you and your interests.
      </p>
      <h6>
        Other Data
      </h6>
      <p>
        While using our Service, we may also collect the following information:
        sex, age, date of birth, place of birth, passport details, citizenship,
        registration at place of residence and actual address, telephone number
        (work, mobile), details of documents on education, qualification,
        professional training, employment agreements, NDA agreements,
        information on bonuses and compensation, information on marital status,
        family members, social security (or other taxpayer identification)
        number, office location and other data.
      </p>
      <h5><b>5.</b> Use of Data</h5>
      <p>
        TaskManagement uses the collected data for various purposes:

        <br />
        <b>0.1.</b> to provide and maintain our Service;

        <br />
        <b>0.2.</b> to notify you about changes to our Service;

        <br />
        <b>0.3.</b> to allow you to participate in interactive features of our
        Service when you choose to do so;

        <br />
        <b>0.4.</b> to provide customer support;

        <br />
        <b>0.5.</b> to gather analysis or valuable information so that we can
        improve our Service;

        <br />
        <b>0.6.</b> to monitor the usage of our Service;

        <br />
        <b>0.7.</b> to detect, prevent and address technical issues;

        <br />
        <b>0.8.</b> to fulfil any other purpose for which you provide it;

        <br />
        <b>0.9.</b> to carry out our obligations and enforce our rights arising
        from any contracts entered into between you and us, including for
        billing and collection;

        <br />
        <b>0.10.</b> to provide you with notices about your account and/or
        subscription, including expiration and renewal notices,
        email-instructions, etc.;

        <br />
        <b>0.11.</b> to provide you with news, special offers and general
        information about other goods, services and events which we offer that
        are similar to those that you have already purchased or enquired about
        unless you have opted not to receive such information;

        <br />
        <b>0.12.</b> in any other way we may describe when you provide the
        information;

        <br />
        <b>0.13.</b> for any other purpose with your consent.
      </p>
      <h5><b>6.</b> Retention of Data</h5>
      <p>
        We will retain your Personal Data only for as long as is necessary for
        the purposes set out in this Privacy Policy. We will retain and use your
        Personal Data to the extent necessary to comply with our legal
        obligations (for example, if we are required to retain your data to
        comply with applicable laws), resolve disputes, and enforce our legal
        agreements and policies. We will also retain Usage Data for internal
        analysis purposes. Usage Data is generally retained for a shorter
        period, except when this data is used to strengthen the security or to
        improve the functionality of our Service, or we are legally obligated to
        retain this data for longer time periods.
      </p>
      <h5><b>7.</b> Transfer of Data</h5>
      <p>
        Your information, including Personal Data, may be transferred to – and
        maintained on – computers located outside of your state, province,
        country or other governmental jurisdiction where the data protection
        laws may differ from those of your jurisdiction. If you are located
        outside Dhaka,Bangladesh and choose to provide information to us, please
        note that we transfer the data, including Personal Data, to
        Dhaka,Bangladesh and process it there. Your consent to this Privacy
        Policy followed by your submission of such information represents your
        agreement to that transfer. TaskManagement will take all the steps
        reasonably necessary to ensure that your data is treated securely and in
        accordance with this Privacy Policy and no transfer of your Personal
        Data will take place to an organisation or a country unless there are
        adequate controls in place including the security of your data and other
        personal information.
      </p>
      <h5><b>8.</b> Disclosure of Data</h5>
      <p>
        We may disclose personal information that we collect, or you provide:

        <br />
        <b>0.1.</b> Business Transaction. If we or our subsidiaries are involved
        in a merger, acquisition or asset sale, your Personal Data may be
        transferred.

        <br />
        <b>0.2.</b> Other cases. We may disclose your information also:

        <br />
        <b>0.2.1.</b> to our subsidiaries and affiliates;

        <br />
        <b>0.2.2.</b> to contractors, service providers, and other third parties
        we use to support our business;

        <br />
        <b>0.2.3.</b> to fulfill the purpose for which you provide it;

        <br />
        <b>0.2.4.</b> for the purpose of including your company’s logo on our
        website;

        <br />
        <b>0.2.5.</b> for any other purpose disclosed by us when you provide the
        information;

        <br />
        <b>0.2.6.</b> with your consent in any other cases;

        <br />
        <b>0.2.7.</b> if we believe disclosure is necessary or appropriate to
        protect the rights, property, or safety of the Company, our customers,
        or others.
      </p>
      <h5><b>9.</b> Security of Data</h5>
      <p>
        The security of your data is important to us but remember that no method
        of transmission over the Internet or method of electronic storage is
        100% secure. While we strive to use commercially acceptable means to
        protect your Personal Data, we cannot guarantee its absolute security.
      </p>
      <h5>
        <b>10.</b> Your Data Protection Rights Under General Data Protection
        Regulation (GDPR)
      </h5>
      <p>
        If you are a resident of the European Union (EU) and European Economic
        Area (EEA), you have certain data protection rights, covered by GDPR. We
        aim to take reasonable steps to allow you to correct, amend, delete, or
        limit the use of your Personal Data. If you wish to be informed what
        Personal Data we hold about you and if you want it to be removed from
        our systems, please email us at taskmanagement@gmail.com. In certain
        circumstances, you have the following data protection rights:

        <br />
        <b>0.1.</b> the right to access, update or to delete the information we
        have on you;

        <br />
        <b>0.2.</b> the right of rectification. You have the right to have your
        information rectified if that information is inaccurate or incomplete;

        <br /><b>0.3.</b> the right to object. You have the right to object to
        our processing of your Personal Data;

        <br />
        <b>0.4.</b> the right of restriction. You have the right to request that
        we restrict the processing of your personal information;

        <br />
        <b>0.5.</b> the right to data portability. You have the right to be
        provided with a copy of your Personal Data in a structured,
        machine-readable and commonly used format;

        <br />
        <b>0.6.</b> the right to withdraw consent. You also have the right to
        withdraw your consent at any time where we rely on your consent to
        process your personal information; Please note that we may ask you to
        verify your identity before responding to such requests. Please note, we
        may not able to provide Service without some necessary data. You have
        the right to complain to a Data Protection Authority about our
        collection and use of your Personal Data. For more information, please
        contact your local data protection authority in the European Economic
        Area (EEA).
      </p>
      <h5>
        <b>11.</b> Your Data Protection Rights under the California Privacy
        Protection Act (CalOPPA)
      </h5>
      <p>
        CalOPPA is the first state law in the nation to require commercial
        websites and online services to post a privacy policy. The law’s reach
        stretches well beyond California to require a person or company in the
        United States (and conceivable the world) that operates websites
        collecting personally identifiable information from California consumers
        to post a conspicuous privacy policy on its website stating exactly the
        information being collected and those individuals with whom it is being
        shared, and to comply with this policy. According to CalOPPA we agree to
        the following:

        <br />
        <b>0.1.</b> users can visit our site anonymously;

        <br />
        <b>0.2.</b> our Privacy Policy link includes the word “Privacy”, and can
        easily be found on the home page of our website;

        <br />
        <b>0.3.</b> users will be notified of any privacy policy changes on our
        Privacy Policy Page;

        <br /><b>0.4.</b> users are able to change their personal information by
        emailing us at taskmanagement@gmail.com. Our Policy on “Do Not Track”
        Signals: We honor Do Not Track signals and do not track, plant cookies,
        or use advertising when a Do Not Track browser mechanism is in place. Do
        Not Track is a preference you can set in your web browser to inform
        websites that you do not want to be tracked. You can enable or disable
        Do Not Track by visiting the Preferences or Settings page of your web
        browser.
      </p>
      <h5>
        <b>12.</b> Your Data Protection Rights under the California Consumer
        Privacy Act (CCPA)
      </h5>
      <p>
        If you are a California resident, you are entitled to learn what data we
        collect about you, ask to delete your data and not to sell (share) it.
        To exercise your data protection rights, you can make certain requests
        and ask us:

        <br /><b>0.1.</b> What personal information we have about you. If you
        make this request, we will return to you:

        <br />
        <b>0.0.1.</b> The categories of personal information we have collected
        about you.

        <br /><b>0.0.2.</b> The categories of sources from which we collect your
        personal information.

        <br /><b>0.0.3.</b> The business or commercial purpose for collecting or
        selling your personal information.

        <br /><b>0.0.4.</b> The categories of third parties with whom we share
        personal information.

        <br /><b>0.0.5.</b> The specific pieces of personal information we have
        collected about you.

        <br /><b>0.0.6.</b> A list of categories of personal information that we
        have sold, along with the category of any other company we sold it to.
        If we have not sold your personal information, we will inform you of
        that fact.

        <br /><b>0.0.7.</b> A list of categories of personal information that we
        have disclosed for a business purpose, along with the category of any
        other company we shared it with. Please note, you are entitled to ask us
        to provide you with this information up to two times in a rolling
        twelve-month period. When you make this request, the information
        provided may be limited to the personal information we collected about
        you in the previous 12 months.

        <br /><b>0.2.</b> To delete your personal information. If you make this
        request, we will delete the personal information we hold about you as of
        the date of your request from our records and direct any service
        providers to do the same. In some cases, deletion may be accomplished
        through de-identification of the information. If you choose to delete
        your personal information, you may not be able to use certain functions
        that require your personal information to operate.

        <br /><b>0.3.</b> To stop selling your personal information. We don’t
        sell or rent your personal information to any third parties for any
        purpose. We do not sell your personal information for monetary
        consideration. However, under some circumstances, a transfer of personal
        information to a third party, or within our family of companies, without
        monetary consideration may be considered a “sale” under California law.
        You are the only owner of your Personal Data and can request disclosure
        or deletion at any time. If you submit a request to stop selling your
        personal information, we will stop making such transfers. Please note,
        if you ask us to delete or stop selling your data, it may impact your
        experience with us, and you may not be able to participate in certain
        programs or membership services which require the usage of your personal
        information to function. But in no circumstances, we will discriminate
        against you for exercising your rights. To exercise your California data
        protection rights described above, please send your request(s) by email:
        taskmanagement@gmail.com. Your data protection rights, described above,
        are covered by the CCPA, short for the California Consumer Privacy Act.
        To find out more, visit the official California Legislative Information
        website. The CCPA took effect on 01/01/2020.
      </p>
      <h5><b>13.</b> Service Providers</h5>
      <p>
        We may employ third party companies and individuals to facilitate our
        Service (“Service Providers”), provide Service on our behalf, perform
        Service-related services or assist us in analysing how our Service is
        used. These third parties have access to your Personal Data only to
        perform these tasks on our behalf and are obligated not to disclose or
        use it for any other purpose.
      </p>
      <h5><b>14.</b> Analytics</h5>
      <p>
        We may use third-party Service Providers to monitor and analyze the use
        of our Service.
      </p>
      <h5><b>15.</b> CI/CD tools</h5>
      <p>
        We may use third-party Service Providers to automate the development
        process of our Service.
      </p>
      <h5><b>16.</b> Behavioral Remarketing</h5>
      <p>
        We may use remarketing services to advertise on third party websites to
        you after you visited our Service. We and our third-party vendors use
        cookies to inform, optimise and serve ads based on your past visits to
        our Service.
      </p>
      <h5><b>17.</b> Payments</h5>
      <p>
        We may provide paid products and/or services within Service. In that
        case, we use third-party services for payment processing (e.g. payment
        processors). We will not store or collect your payment card details.
        That information is provided directly to our third-party payment
        processors whose use of your personal information is governed by their
        Privacy Policy. These payment processors adhere to the standards set by
        PCI-DSS as managed by the PCI Security Standards Council, which is a
        joint effort of brands like Visa, Mastercard, American Express and
        Discover. PCI-DSS requirements help ensure the secure handling of
        payment information.
      </p>
      <h5>18. Links to Other Sites</h5>
      <p>
        Our Service may contain links to other sites that are not operated by
        us. If you click a third party link, you will be directed to that third
        party’s site. We strongly advise you to review the Privacy Policy of
        every site you visit. We have no control over and assume no
        responsibility for the content, privacy policies or practices of any
        third party sites or services. For example, the outlined privacy policy
        has been made using PolicyMaker.io, a free tool that helps create
        high-quality legal documents. PolicyMaker’s privacy policy generator is
        an easy-to-use tool for creating a privacy policy for blog, website,
        e-commerce store or mobile app.
      </p>
      <h5><b>19.</b> Children’s Privacy</h5>
      <p>
        Our Services are not intended for use by children under the age of 18
        (“Child” or “Children”). We do not knowingly collect personally
        identifiable information from Children under 18. If you become aware
        that a Child has provided us with Personal Data, please contact us. If
        we become aware that we have collected Personal Data from Children
        without verification of parental consent, we take steps to remove that
        information from our servers.
      </p>
      <h5><b>20.</b> Changes to This Privacy Policy</h5>
      <p>
        We may update our Privacy Policy from time to time. We will notify you
        of any changes by posting the new Privacy Policy on this page. We will
        let you know via email and/or a prominent notice on our Service, prior
        to the change becoming effective and update “effective date” at the top
        of this Privacy Policy. You are advised to review this Privacy Policy
        periodically for any changes. Changes to this Privacy Policy are
        effective when they are posted on this page.
      </p>
      <h5>21. Contact Us</h5>
      <p>
        If you have any questions about this Privacy Policy, please contact us
        by email: taskmanagement@gmail.com.
      </p>
      <small>
        This Privacy Policy was created for TaskManagement.com by PolicyMaker.io
        on 2021-12-01.
      </small>
    </div>
  </div>
</template>

<script>
export default {
  name: "Privacy",
};
</script>

<style lang="scss" scoped>
@import "../../scss/index";
</style>
