<template>
<div class="py-3">
  <div class="top-bar">
    <li class="list-item">Setting</li>
    <li class="list-item" @click="scrollToElement">Privacy</li>
    <li class="list-item" @click="scrollToTearms">Tearms & Conditions</li>
  </div>

<!--  Privacy section-->
  <section id="general">
    <div class="container">
      <h2 class="head pb-2"><b>Notification</b></h2>
      <p>Notification off</p>
      <div id="dark-btn"  >
        <span @click="hover" v-bind:class="{'darkbtnon' : isactive}"></span>
      </div>
    </div>

  </section>



  <section id="privacy" ref="scrollToMe">
    <div class="container">
      <h2 class="head pb-2"><b>Privacy & Policy</b></h2>
      <h3 class="mb-2">TaskManagement User Privacy & Policy</h3>
      <small >
        <b>Effective Date: December 1, 2021</b>
      </small>
      <h5 class="mt-2">
        <b>1.</b> Introduction</h5>

      <h6>Welcome to TaskManagement.
        <br>
        TaskManagement (“us”, “we”, or “our”) operates TaskManagement.com (hereinafter referred to as “Service”).</h6>
      <p>Our Privacy Policy governs your visit to TaskManagement.com, and explains how we collect, safeguard and disclose information that results from your use of our Service.

        We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.

        Our Terms and Conditions (“Terms”) govern all use of our Service and together with the Privacy Policy constitutes your agreement with us (“agreement”).

      </p>
      <h5><b>2.</b> Definitions
      </h5>
      <h6>SERVICE means the TaskManagement.com website operated by TaskManagement.</h6>
      <p>ERSONAL DATA means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).

        USAGE DATA is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).

        COOKIES are small files stored on your device (computer or mobile device).

        DATA CONTROLLER means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.

        DATA PROCESSORS (OR SERVICE PROVIDERS) means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.

        DATA SUBJECT is any living individual who is the subject of Personal Data.

        THE USER is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.
      </p>
      <h5><b>3.</b> Information Collection and Use</h5>
      <p>
        We collect several different types of information for various purposes to provide and improve our Service to you.</p>
      <h5><b>4.</b> Types of Data Collected</h5>
      <h6>Personal Data : </h6>
      <p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (“Personal Data”). Personally identifiable information may include, but is not limited to:
        <br>
        <b>0.1.</b> Email address
        <br>
        <b>0.2.</b> First name and last name
        <br>
        <b>0.3.</b> Phone number
        <br>
        <b>0.4.</b> Address, Country, State, Province, ZIP/Postal code, City
        <br>
        <b>0.5.</b> Cookies and Usage Data
        <br>
        We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link.

        Usage Data

        We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through any device (“Usage Data”).

        This Usage Data may include information such as your computer’s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.

        When you access Service with a device, this Usage Data may include information such as the type of device you use, your device unique ID, the IP address of your device, your device operating system, the type of Internet browser you use, unique device identifiers and other diagnostic data.
      </p>
      <h6>Tracking Cookies Data</h6>
      <p>We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.

        Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze our Service.

        You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.

        Examples of Cookies we use:

        <br> <b>0.1.</b> Session Cookies: We use Session Cookies to operate our Service.

        <br> <b>0.2.</b> Preference Cookies: We use Preference Cookies to remember your preferences and various settings.

        <br><b>0.3.</b> Security Cookies: We use Security Cookies for security purposes.

        <br> <b>0.4.</b> Advertising Cookies: Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.</p>
      <h6>
        Other Data</h6>
      <p>While using our Service, we may also collect the following information: sex, age, date of birth, place of birth, passport details, citizenship, registration at place of residence and actual address, telephone number (work, mobile), details of documents on education, qualification, professional training, employment agreements, NDA agreements, information on bonuses and compensation, information on marital status, family members, social security (or other taxpayer identification) number, office location and other data.
      </p>
      <h5>
        <b>5.</b> Use of Data
      </h5>
      <p>TaskManagement uses the collected data for various purposes:

        <br> <b>0.1.</b> to provide and maintain our Service;

        <br> <b>0.2.</b> to notify you about changes to our Service;

        <br>  <b>0.3.</b> to allow you to participate in interactive features of our Service when you choose to do so;

        <br>  <b>0.4.</b> to provide customer support;

        <br> <b>0.5.</b> to gather analysis or valuable information so that we can improve our Service;

        <br> <b>0.6.</b> to monitor the usage of our Service;

        <br> <b>0.7.</b> to detect, prevent and address technical issues;

        <br> <b>0.8.</b> to fulfil any other purpose for which you provide it;

        <br>  <b>0.9.</b> to carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection;

        <br>  <b>0.10.</b> to provide you with notices about your account and/or subscription, including expiration and renewal notices, email-instructions, etc.;

        <br> <b>0.11.</b> to provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information;

        <br>  <b>0.12.</b> in any other way we may describe when you provide the information;

        <br> <b>0.13.</b> for any other purpose with your consent.</p>
      <h5>
        <b>6.</b> Retention of Data</h5>
      <p>We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.

        We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.
      </p>
      <h5><b>7.</b> Transfer of Data</h5>
      <p>Your information, including Personal Data, may be transferred to – and maintained on – computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.

        If you are located outside Dhaka,Bangladesh and choose to provide information to us, please note that we transfer the data, including Personal Data, to Dhaka,Bangladesh and process it there.

        Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.

        TaskManagement will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.

      </p>
      <h5><b>8.</b> Disclosure of Data</h5>
      <p>We may disclose personal information that we collect, or you provide:

        <br> <b>0.1.</b> Business Transaction.

        If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.

        <br>   <b>0.2.</b> Other cases. We may disclose your information also:

        <br>  <b>0.2.1.</b> to our subsidiaries and affiliates;

        <br> <b>0.2.2.</b> to contractors, service providers, and other third parties we use to support our business;

        <br> <b>0.2.3.</b> to fulfill the purpose for which you provide it;

        <br> <b>0.2.4.</b> for the purpose of including your company’s logo on our website;

        <br> <b>0.2.5.</b> for any other purpose disclosed by us when you provide the information;

        <br> <b>0.2.6.</b> with your consent in any other cases;

        <br> <b>0.2.7.</b> if we believe disclosure is necessary or appropriate to protect the rights, property, or safety of the Company, our customers, or others.

      </p>
      <h5>
        <b>9.</b> Security of Data</h5>
      <p>The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.

      </p>
      <h5><b>10.</b> Your Data Protection Rights Under General Data Protection Regulation (GDPR)
      </h5>
      <p>If you are a resident of the European Union (EU) and European Economic Area (EEA), you have certain data protection rights, covered by GDPR.

        We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.

        If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please email us at taskmanagement@gmail.com.

        In certain circumstances, you have the following data protection rights:

        <br> <b>0.1.</b> the right to access, update or to delete the information we have on you;

        <br> <b>0.2.</b> the right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete;

        <br><b>0.3.</b> the right to object. You have the right to object to our processing of your Personal Data;

        <br>  <b>0.4.</b> the right of restriction. You have the right to request that we restrict the processing of your personal information;

        <br>  <b>0.5.</b> the right to data portability. You have the right to be provided with a copy of your Personal Data in a structured, machine-readable and commonly used format;

        <br> <b>0.6.</b> the right to withdraw consent. You also have the right to withdraw your consent at any time where we rely on your consent to process your personal information;

        Please note that we may ask you to verify your identity before responding to such requests. Please note, we may not able to provide Service without some necessary data.

        You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).

      </p>
      <h5><b>11.</b> Your Data Protection Rights under the California Privacy Protection Act (CalOPPA)</h5>
      <p>CalOPPA is the first state law in the nation to require commercial websites and online services to post a privacy policy. The law’s reach stretches well beyond California to require a person or company in the United States (and conceivable the world) that operates websites collecting personally identifiable information from California consumers to post a conspicuous privacy policy on its website stating exactly the information being collected and those individuals with whom it is being shared, and to comply with this policy.

        According to CalOPPA we agree to the following:

        <br> <b>0.1.</b> users can visit our site anonymously;

        <br> <b>0.2.</b> our Privacy Policy link includes the word “Privacy”, and can easily be found on the home page of our website;

        <br> <b>0.3.</b> users will be notified of any privacy policy changes on our Privacy Policy Page;

        <br><b>0.4.</b> users are able to change their personal information by emailing us at taskmanagement@gmail.com.

        Our Policy on “Do Not Track” Signals:

        We honor Do Not Track signals and do not track, plant cookies, or use advertising when a Do Not Track browser mechanism is in place. Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked.

        You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.</p>
      <h5><b>12.</b> Your Data Protection Rights under the California Consumer Privacy Act (CCPA)</h5>
      <p>If you are a California resident, you are entitled to learn what data we collect about you, ask to delete your data and not to sell (share) it. To exercise your data protection rights, you can make certain requests and ask us:

        <br><b>0.1.</b> What personal information we have about you. If you make this request, we will return to you:

        <br> <b>0.0.1.</b> The categories of personal information we have collected about you.

        <br><b>0.0.2.</b> The categories of sources from which we collect your personal information.

        <br><b>0.0.3.</b> The business or commercial purpose for collecting or selling your personal information.

        <br><b>0.0.4.</b> The categories of third parties with whom we share personal information.

        <br><b>0.0.5.</b> The specific pieces of personal information we have collected about you.

        <br><b>0.0.6.</b> A list of categories of personal information that we have sold, along with the category of any other company we sold it to. If we have not sold your personal information, we will inform you of that fact.

        <br><b>0.0.7.</b> A list of categories of personal information that we have disclosed for a business purpose, along with the category of any other company we shared it with.

        Please note, you are entitled to ask us to provide you with this information up to two times in a rolling twelve-month period. When you make this request, the information provided may be limited to the personal information we collected about you in the previous 12 months.

        <br><b>0.2.</b> To delete your personal information. If you make this request, we will delete the personal information we hold about you as of the date of your request from our records and direct any service providers to do the same. In some cases, deletion may be accomplished through de-identification of the information. If you choose to delete your personal information, you may not be able to use certain functions that require your personal information to operate.

        <br><b>0.3.</b> To stop selling your personal information. We don’t sell or rent your personal information to any third parties for any purpose. We do not sell your personal information for monetary consideration. However, under some circumstances, a transfer of personal information to a third party, or within our family of companies, without monetary consideration may be considered a “sale” under California law. You are the only owner of your Personal Data and can request disclosure or deletion at any time.

        If you submit a request to stop selling your personal information, we will stop making such transfers.

        Please note, if you ask us to delete or stop selling your data, it may impact your experience with us, and you may not be able to participate in certain programs or membership services which require the usage of your personal information to function. But in no circumstances, we will discriminate against you for exercising your rights.

        To exercise your California data protection rights described above, please send your request(s) by email: taskmanagement@gmail.com.

        Your data protection rights, described above, are covered by the CCPA, short for the California Consumer Privacy Act. To find out more, visit the official California Legislative Information website. The CCPA took effect on 01/01/2020.
      </p>
      <h5><b>13.</b> Service Providers</h5>
      <p>We may employ third party companies and individuals to facilitate our Service (“Service Providers”), provide Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.

        These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
      </p>
      <h5><b>14.</b> Analytics</h5>
      <p>We may use third-party Service Providers to monitor and analyze the use of our Service.</p>
      <h5><b>15.</b> CI/CD tools</h5>
      <p>We may use third-party Service Providers to automate the development process of our Service.</p>
      <h5>
        <b>16.</b> Behavioral Remarketing
      </h5>
      <p>We may use remarketing services to advertise on third party websites to you after you visited our Service. We and our third-party vendors use cookies to inform, optimise and serve ads based on your past visits to our Service.
      </p>
      <h5>
        <b>17.</b> Payments</h5>
      <p>We may provide paid products and/or services within Service. In that case, we use third-party services for payment processing (e.g. payment processors).

        We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.
      </p>
      <h5>18. Links to Other Sites</h5>
      <p>Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party’s site. We strongly advise you to review the Privacy Policy of every site you visit.

        We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.

        For example, the outlined privacy policy has been made using PolicyMaker.io, a free tool that helps create high-quality legal documents. PolicyMaker’s privacy policy generator is an easy-to-use tool for creating a privacy policy for blog, website, e-commerce store or mobile app.
      </p>
      <h5><b>19.</b> Children’s Privacy
      </h5>
      <p>Our Services are not intended for use by children under the age of 18 (“Child” or “Children”).

        We do not knowingly collect personally identifiable information from Children under 18. If you become aware that a Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from Children without verification of parental consent, we take steps to remove that information from our servers.

      </p>
      <h5><b>20.</b> Changes to This Privacy Policy</h5>
      <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.

        We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update “effective date” at the top of this Privacy Policy.

        You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.

      </p>
      <h5>21. Contact Us</h5>
      <p>
        If you have any questions about this Privacy Policy, please contact us by email: taskmanagement@gmail.com.</p>
      <small>

        This Privacy Policy was created for TaskManagement.com by PolicyMaker.io on 2021-12-01.
      </small>
    </div>
  </section>

<!--  Tearms & Conditins-->

  <section id="tearms" ref="scrolltotearms">
    <div class="container">
      <h2 class="head pb-2"><b>Terms & Conditions</b></h2>
      <h3 class="pb-1">TaskManagement User Terms of Service</h3>
      <small>
        <b>Effective Date: December 1, 2021</b></small>
      <p>
        TaskManagement, Inc. (“TaskManagement,” “we,” “our”) offers a variety of team productivity, collaboration, and organizational tools available online, including via a mobile application (collectively, the “Service”), and websites, including but not limited to www.TaskManagement.com, wavelength.com, blog.TaskManagement.com, community.TaskManagement.com (the “Websites”). TaskManagement, Inc. is located at 633 Folsom Street Suite 100, San Francisco, CA 94107-3600. If you have any questions about these User Terms of Service (the “Terms”), please email us at terms-questions@TaskManagement.com. TaskManagement has three different types of users depending on the TaskManagement products used:
      </p>
      <ul>
        <li> We call users of the Websites “Site Visitors.” </li>
        <li> We call users who use the free version of the TaskManagement Service “Free Users.” While Free Users can access and use the Service, they have access to a more limited set of Service features and functionality than Subscribers.
        </li>
        <li>  We call users who use the Service as part of a paid TaskManagement subscription plan (regardless of the subscription tier) “Subscribers.” The Service features and functionalities available to Subscribers are determined by the subscription tier and the specific terms agreed to between TaskManagement and the organization (e.g., your employer or another entity or person, called the “Customer”) that entered into a separate agreement that governs delivery, access, and use of the Service (the “Customer Agreement”).
        </li>
      </ul>
      <p>
        We refer to these three types of users collectively as “Users” or “you” for purposes of these Terms. Regardless of what type of User you are, these Terms create a legal agreement directly between you and TaskManagement and explain the rules governing use of the Service and Websites. By accessing or using the Service and Websites, you acknowledge and agree that you have read, understand, and agree to be bound by these Terms and our Privacy Policy. If you do not agree to these Terms, please do not access or use the Service and Websites. We may, from time to time, modify these Terms. Please check this page periodically for updates. We will comply with applicable local legal obligations to provide you with notice of changes to these Terms. Your continued use of the Service and Websites after any such update constitutes your acceptance of such changes.
      </p>
      <h5><b>1.</b> ELIGIBILITY AND SCOPE</h5>
      <p><b>1.1</b> General. To use the Service and Websites you must be, and represent and warrant that you are, at least 13 years of age and competent to agree to these Terms. If TaskManagement has previously prohibited you from accessing or using the Service and Websites, you are not permitted to access or use the Service and Websites. 1.2 Location. These Terms are applicable to Users outside of the United States. If you are located in the United States, the terms available at https://TaskManagement.com/terms#terms-of-service apply to you.
      </p>
      <h5><b>2.</b> ACCOUNT REGISTRATION AND USE</h5>
      <p><b>2.1</b> Account Registration and Confidentiality. To access the Service and Websites, you must register for an TaskManagement account by creating a user name and password. You agree to provide us with accurate, complete, and current registration information about yourself. It is your responsibility to ensure that your password remains confidential and secure. By registering, you agree that you are fully responsible for all activities that occur under your user name and password. We may assume that any communications we receive under your account have been made by you. If you are a billing owner, an administrator, or if you have confirmed in writing that you have the authority to make decisions on behalf of a Customer (“Account Administrator”), you represent and warrant that you are authorized to make decisions on behalf of the Customer and agree that TaskManagement is entitled to rely on your instructions.
      </p><p> 2.2 Unauthorized Account Use. You are responsible for notifying us at terms-questions@TaskManagement.com if you become aware of any unauthorized use of or access to your account. You understand and agree that we may require you to provide information that may be used to confirm your identity and help ensure the security of your account. TaskManagement will not be liable for any loss, damages, liability, expenses or attorneys’ fees that you may incur as a result of someone else using your password or account, either with or without your knowledge and/or authorization, and regardless of whether you have or have not advised us of such unauthorized use. You will be liable for losses, damages, liability, expenses and attorneys’ fees incurred by TaskManagement or a third party due to someone else using your account. In the event that the Account Administrator or Customer loses access to an account or otherwise requests information about an account, TaskManagement reserves the right to request from the Account Administrator or Customer any verification it deems necessary before restoring access to or providing information about such account in its sole discretion.
    </p>
      <h5><b>3.</b> OUR PROPRIETARY RIGHTS</h5>
      <p><b>3.1</b> The Service and Websites are owned and operated by TaskManagement and contain materials (including all software, design, text, editorial materials, informational text, photographs, illustrations, audio clips, video clips, artwork and other graphic materials, and names, logos, trademarks and services marks) which are derived in whole or in part from materials supplied by TaskManagement and its partners, as well as other sources, and are protected by United States copyright laws, international treaty provisions, trademarks, service marks and other intellectual property laws. The Service and Websites are also protected as a collective work or compilation under U.S. and global copyright and other law and treaties. You agree to abide by all applicable copyright and other laws, as well as any additional copyright notices or restrictions contained in the Service and Websites. You acknowledge that the Service and Websites have been developed, compiled, prepared, revised, selected, and arranged by TaskManagement and others through the application of methods and standards of judgment developed and applied through the expenditure of substantial time, effort, and money and constitute valuable intellectual property of TaskManagement and such others. You agree to notify TaskManagement immediately upon becoming aware of any claim that the Service and Websites infringe upon any copyright, trademark, or other contractual, statutory, or common law rights. Any unauthorized use of any material contained on or through the Service and Websites may violate copyright laws, trademark laws, the laws of privacy and publicity and communications regulations and statutes.
      </p>
      <h5><b>4.</b> USER CONTENT AND FEEDBACK</h5>
      <p><b>4.1</b> User Content and Submissions on the Service. The Service allows you to create tasks and submit associated information, text, files, and other materials (collectively, “User Content”) and to share that User Content with others. User Content submitted or otherwise made available to the Service is subject to the following terms:

        <b>4.1.1</b> Free User Content. Free Users maintain ownership of the User Content that they submit to the Service (“Free User Content”). By submitting Free User Content, Free Users grant TaskManagement a license to access, use, copy, reproduce, process, adapt, publish, transmit, and display that Free User Content, as permitted by TaskManagement’s Privacy Policy, including if required to do so by law or in good faith to comply with legal process. We reserve the right to remove any Free User Content on the Service that violates these Terms or that is otherwise objectionable in TaskManagement’s sole discretion.

        <b>4.1.2</b> Subscriber User Content on the Service. Content submitted to the Service by Subscribers (“Subscriber User Content”) is owned and controlled by the Customer as set forth in the introduction to these Terms and the Customer Agreement, except with respect to Subscriber User Content submitted by students pursuant to a Customer Agreement with an educational institution (“Student Content”). Such Student Content is owned by the student and not the educational institution. TaskManagement maintains a limited, non-exclusive and non-transferrable (except in connection with the sale or transfer of its business) license to access, use, copy, reproduce, process, adapt, publish, transmit, host, and display Subscriber User Content for the following limited purposes: (i) to maintain, provide and improve the Service; (ii) to prevent or address technical or security issues and resolve support requests; (iii) to investigate when we have a good faith belief, or have received a complaint alleging, that such Subscriber User Content is in violation of the Customer Agreement or these Terms; (iv) to comply with a valid legal subpoena, request, or other lawful process that meets the requirements of the Customer Agreement and our Law Enforcement Guidelines; and (v) as otherwise set forth in our Customer Agreement or as expressly permitted in writing by the Customer.
      </p>
      <p><b>4.2</b> Feedback on the Websites. The Websites may have certain features that allow you to submit comments, information, and other materials (collectively, “Feedback”) to TaskManagement and share such Feedback with other users, or the public. By submitting Feedback through the Websites, you grant TaskManagement a license to access, use, copy, reproduce, process, adapt, publish, transmit, host, and display that Feedback for any purpose (including in testimonials or other TaskManagement marketing materials and where required to do so by law or in good faith to comply with legal process.). We reserve the right to remove any Feedback posted in public forums for any reason at our sole discretion.
      </p>
      <p><b>4.3</b> User Content and Feedback Representations. You acknowledge and agree that you have all required rights to submit User Content and Feedback without violation of any third-party rights. You understand that TaskManagement does not control, and is not responsible for, User Content or Feedback, and that by using the Service and/or Websites, you may be exposed to User Content or Feedback from other users that is offensive, indecent, inaccurate, misleading, or otherwise objectionable. Please also note that User Content and Feedback may contain typographical errors, other inadvertent errors or inaccuracies. You agree that you will indemnify, defend, and hold harmless TaskManagement for all claims resulting from User Content or Feedback you submit through the Service and/or Websites. We reserve the right, at our own expense, to assume the exclusive defense and control of such disputes, and in any event you will cooperate with us in asserting any available defenses.
      </p>
      <h5><b>5.</b> LICENSE AND ACCEPTABLE USE</h5>
      <p><b>5.1</b> Your License. Subject to your compliance with these Terms, we grant you a limited, non-exclusive, non-sublicensable, non-transferable, and revocable license to access and use the Service and Websites only for your own internal use (or, for Subscribers, uses authorized by the Customer), and only in a manner that complies with all legal requirements that apply to you or your use of the Service and Websites, including the TaskManagement Privacy Policy and these Terms. TaskManagement may revoke this license at any time, in its sole discretion.
      </p>
      <p><b>5.2</b> Acceptable Use. All Users must comply with the following rules regarding acceptable use of the Service and Websites.
      </p>
      <h5>
        Disruption of the Service. You may not:</h5>
      <p>access, tamper with, or use non-public areas of the Service and Websites, TaskManagement’s computer systems, or the technical delivery systems of TaskManagement’s providers;
        probe, scan, or test the vulnerability of any system or network or breach or circumvent any security or authentication measure;
        access or search the Service and Websites by any means other than TaskManagement’s publicly supported interfaces (for example, “scraping”);
        attempt to disrupt or overwhelm our infrastructure by intentionally imposing unreasonable requests or burdens on our resources (e.g. using “bots” or other automated systems to send requests to our servers at a rate beyond what could be sent by a human user during the same period of time); or
        interfere with or disrupt the access of any user, host or network, including, without limitation, by sending a virus, overloading, flooding, spamming, mail-bombing the Service and Websites, or by scripting the creation of User Content in such a manner as to interfere with or create an undue burden on the Service and Websites.
      </p>
      <h5>Misuse of the Service and Websites. You may not utilize the Service and Websites to carry out, promote or support:
      </h5>
      <p><b>any unlawful or fraudulent activities;</b>
        the impersonation of another person or entity or the misrepresentation of an affiliation with a person or entity in a manner that does or is intended to mislead, confuse, or deceive others;
        activities that are defamatory, libelous or threatening, constitute hate speech, harassment, or stalking;
        the publishing or posting of other people’s private or personal information without their express authorization and permission;
        the sending of unsolicited communications, promotions advertisements, or spam;
        the publishing of or linking to malicious content intended to damage or disrupt another user’s browser or computer; or
        the promotion or advertisement of products or services other than your own without appropriate authorization.
      </p>
      <h5>User Content Standards Within the Service and Websites. You may not post any User Content on the Service or Websites that:
      </h5>
      <p><b>violates any applicable law, any third party’s intellectual property rights, or anyone’s right of privacy or publicity;</b>
        is deceptive, fraudulent, illegal, obscene, pornographic (including child pornography, which, upon becoming aware of, we will remove and report to law enforcement, including the National Center for Missing and Exploited children), defamatory, libelous or threatening, constitutes hate speech, harassment, or stalking;
        contains any personal information of minors;
        contains any sensitive personal information, such as financial information, payment card numbers, social security numbers, or health information without TaskManagement’s prior written consent granted as part of a Customer Agreement;
        contains viruses, bots, worms, or similar harmful materials; or
        contains any information that you do not have a right to make available under law or any contractual or fiduciary duty.
      </p>
      <p>Violations of this Section 5. In addition to any other remedies that may be available to us, TaskManagement reserves the right to take any remedial action it deems necessary, including immediately suspending or terminating your account or your access to the Service or Websites, upon notice and without liability for TaskManagement should you fail to abide by the rules in this Section 5 or if, in TaskManagement’s sole discretion, such action is necessary to prevent disruption of the Service or Websites for other users. If you are a Subscriber, TaskManagement reserves the right to notify the Customer’s Account Administrator(s) or other Customer representative(s) of any violations of these Terms.
      </p>
      <h5><b>6.</b> PRIVACY</h5>
      <p>For information about how we collect, use, and share the data we collect from and about you, please see our Privacy Policy which is incorporated by reference into these Terms.
      </p>
      <h5><b>7.</b> LIMITATION OF LIABILITY</h5>
      <p>If we fail to comply with these Terms, we are responsible for loss or damage that you suffer that is a foreseeable result of our breach of these Terms or our negligence, but we are not responsible for any loss or damage that is not foreseeable. Loss or damage is foreseeable if it is an obvious consequence of our breach or if it was an order that was accepted. We also only provide the Service and Websites for your internal use. We have no liability to you for any loss of profit, loss of business, business interruption or loss of business opportunity based on your use of or reliance on the Service and Websites. We do not exclude or limit in any way our liability to you where it would be unlawful for us to do so. This includes liability for death or personal injury caused by our negligence or the negligence of our employees, agents or subcontractors, for fraud or fraudulent misrepresentation and for breach of your legal rights in relation to the Service and Websites.

        The information presented on or through the Service and Websites is made available solely for general information purposes. We do not confirm the accuracy, completeness or usefulness of this information. Any reliance that you place on such information is strictly at your own risk.
      </p>
      <h5><b>8.</b> VIRUSES</h5>
      <p>
        You understand that we cannot and do not guarantee that files available for downloading from the Internet or our Service or Websites will be free of viruses or other destructive code. You are responsible for implementing sufficient procedures and checkpoints to satisfy your particular requirements for anti-virus protection and accuracy of data input and output, and for maintaining a means external to the Service and Websites for any reconstruction of any lost data.
      </p>
      <h5><b>9.</b> THIRD-PARTY LINKS AND SERVICE AND WEBSITES</h5>
      <p>The Service and Websites may provide (1) information and content provided by third parties; (2) links to third-party websites or resources, such as sellers of goods and services; and (3) third-party products and services for sale directly to you. TaskManagement is not responsible for the availability of such external sites or resources, and does not endorse and is not responsible or liable for (i) any content, advertising, products, or other materials on or available from such sites or resources, (ii) any errors or omissions in these websites or resources, or (iii) any information handling practices or other business practices of the operators of such sites or resources. You further acknowledge and agree that TaskManagement shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any linked sites or resources. Your interactions with such third parties will be governed by the third parties’ own terms of service and privacy policies, and any other similar terms.</p>
      <h5><b>10.</b> MODIFICATION</h5>
      <p>TaskManagement reserves the right at any time to modify or discontinue, temporarily or permanently, the Service and Websites (or any part thereof), with or without notice. You agree that TaskManagement shall not be liable to you or any third party for any modification, suspension or discontinuance of the Service and Websites.
      </p>
      <h5><b>11.</b> APPLICABLE LAW
      </h5>
      <p>Please note that these Terms, and their subject matter and formation, are governed by the laws of Ireland. However, if you are a consumer and resident of any other European country you will benefit from, and if you are a consumer and resident of any country in APAC or the UAE you may benefit from, any mandatory provisions of, and legal rights available to you under, the laws of that country. Nothing in these Terms affects your rights as a consumer to rely on any such local law mandatory provisions and legal rights.

        You can contact TaskManagement at dispute-notice@TaskManagement.com if you have any complaints or disputes about the Services. You and TaskManagement shall use best efforts to settle any dispute, claim, question, or disagreement directly through consultation and good faith negotiations, which shall be a precondition to either party initiating a lawsuit or other form of complaint. If we do not reach an agreed-upon solution within a period of 30 days from the time informal dispute resolution is pursued, to the extent permitted by applicable law, all controversies, disputes, demands, counts, claims or causes of action between you and TaskManagement arising out of, under, or related to the Services shall be submitted to the exclusive jurisdiction of the courts of Ireland. However, if you are a resident of any other European country, APAC country or the UAE, you may also bring proceedings in that country.
      </p>
      <h5><b>12.</b> GENERAL TERMS</h5>
      <p><b>12.1.</b> No waiver. If we fail to insist that you perform any obligations under these Terms, or if we do not enforce our rights against you, or if we delay in doing so, that will not mean that we have waived such rights and will not mean that you do not have to comply with your obligations. If we do waive a failure or breach by you, we will only do so in writing and that will not mean that we automatically waive any future failure of breach by you.
      </p>
      <p><b>12.2.</b> Severability. Each of the paragraphs of these Terms operates separately. If any court or relevant authority decides that any of them are unlawful or unenforceable, the remaining paragraphs will remain in full force and effect.
      </p>
      <p><b>12.3.</b> Miscellaneous. The section titles in these Terms are for convenience only and have no legal or contractual effect.
      </p>
      <p><b>12.4. </b>Notices. We may deliver notice to you by e-mail, posting a notice on the Service and Websites or any other method we choose and such notice will be effective on dispatch. If you give notice to us, it will be effective when received and you must use the following physical or email address: (1) TaskManagement, Inc. 633 Folsom Street Suite 100, San Francisco, CA 94107-3600; or (2) terms-questions@TaskManagement.com.
      </p>

    </div>
  </section>

</div>
</template>

<script>


export default {
name: "Setting",
  data(){
  return{
    isactive : false
  }
  },
  mounted() {
    this.scrollToElement();
    this.scrollToTearms();
  },
  methods: {
    scrollToElement() {
      const el = this.$refs.scrollToMe;

      if (el ) {
        // Use el.scrollIntoView() to instantly scroll to the element
        el.scrollIntoView({behavior: 'smooth'});

      }
      // else{
      //   this.el = this.$refs.scrollToMe[0];
      // }
    },

    // scrollToTearms() {
    //   const el = this.$refs.scrolltotearms;
    //
    //   if (el  ) {
    //     // Use el.scrollIntoView() to instantly scroll to the element
    //     el.scrollIntoView({behavior: 'smooth'});
    //
    //     // else{
    //     //  this.el = this.$refs.scrolltotearms[0];
    //     // }
    //   }
    //
    // },
    scrollToTearms (to, from, savedPosition) {
      savedPosition = this.$refs.scrolltotearms;
      if (savedPosition) {
        return savedPosition.scrollIntoView({behavior: 'smooth'});

      } else {
        return this.$refs.scrolltotearms[0];
      }
    },
    hover(){
      this.isactive = !this.isactive
    }
  }

}
</script>

<style scoped>
.top-bar{
  padding: 50px;
  position: fixed;

}
.list-item{
  list-style: none;
  padding: 10px;
  border-radius: 10px;
  margin-bottom: 10px;
  border: 1px solid black;
  cursor: pointer;
}

.list-item:hover{
  background-color: black;
  color: white;
  transition: 0.5s;
  -moz-transition: 0.5s;
  -webkit-transition: 0.5s;
}

#privacy p{
  word-break: break-all;
}
#privacy{
  margin-bottom: 50px;
}
.container{
  border-left: 1px solid black;
  padding-left: 20px;
}

#general .container{
  height: 50vh;
}

#dark-btn{

  background-color: #ccc;
  width: 45px;
  border-radius: 15px;
  padding: 2px 3px;
  cursor: pointer;
  display: flex;
  transition: padding-left 0.5s, background 0.5s;
}
#dark-btn span{
  width: 18px;
  height: 18px;
  background: #fff;
  border-radius: 50%;
  display: inline-block;
}

.darkbtnon{
  margin-left: 23px;
  background-color: #0a0a0a;
  transition: 0.5s;
}

@media (min-width:576px)and (max-width:991px){
  .top-bar{
    padding: 30px;
    width: 100%;
    display: flex;
    flex-direction: row;
    border-bottom: 1px solid black;
    border-right: none;
    background-color: white;
    margin-top: -18px;
  }
  .list-item{
    list-style: none;
    height: 35px;
    padding: 5px;
    border-radius: 10px;
    margin-right: 10px;
    border: 1px solid black;
    cursor: pointer;
  }
  #privacy{
    margin: 120px 0 30px 0;
  }
}
@media  (max-width: 576px){
  .top-bar{
    padding: 10px;
    width: 100%;
    display: flex;
    flex-direction: row;
    border-bottom: 1px solid black;
    border-right: none;
    background-color: white;
    margin-top: -17px;
  }
  .list-item{
    list-style: none;
    height: 35px;
    padding: 5px;
    border-radius: 10px;
    margin-right: 10px;
    border: 1px solid black;
    cursor: pointer;
  }
  #privacy{
    margin: 60px 0 30px 0;
  }
}
</style>
